# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='categories_sub_categories_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipie_Recipie_subtype_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='recipie_subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie_subtype_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Recipie_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='recipies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie_name', models.CharField(max_length=60)),
                ('ingredients', models.CharField(max_length=1000)),
                ('preparation', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipies_Rmap_Cmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_map_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipie.categories_sub_categories_map')),
                ('R_map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.Recipie_Recipie_subtype_map')),
                ('Recipie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.recipies')),
            ],
        ),
        migrations.CreateModel(
            name='sub_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categorie_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='recipie_recipie_subtype_map',
            name='R_subtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.recipie_subtype'),
        ),
        migrations.AddField(
            model_name='recipie_recipie_subtype_map',
            name='Recipietype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.Recipie_Type'),
        ),
        migrations.AddField(
            model_name='categories_sub_categories_map',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.sub_categories'),
        ),
    ]
