# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='recipie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.recipie_subtype'),
        ),
    ]
