# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0003_auto_20170703_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_categories',
            old_name='subcategorie_name',
            new_name='subcategory_name',
        ),
    ]
