# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0004_auto_20170703_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies_rmap_cmap',
            name='Recipie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.Recipie_Type'),
        ),
    ]
