# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0005_auto_20170704_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_sub_categories_map',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipie.Categories'),
        ),
    ]
